<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
</head>
<style>
	svg {
    	border: 1px solid red;
    
    }
</style>
<body>
    <h1>3WA Painter</h1>
	<svg height="600px" width="800px">
		<?php foreach($results as $result) {?>
			<?= $result ?>
		<?php }?>
	</svg>	
</body>
</html>

<!--

<rect x="50" y="20" width="200" height="100" fill="firebrick" opacity="1"></rect>
		<rect x="400px" y="200px" width="100" height="100" fill="deepskyblue" opacity="0.5"></rect>
		<circle cx="300px" cy="250px" r="180" height="100" fill="gold" opacity="0.33"></circle>
		<ellipse cx="600px" cy="250px" rx="40" ry="80" fill="seagreen" opacity="1"></ellipse>
		<polygon points="60 60, 200 250, 60 250" fill="purple" opacity="0.75"></polygon>
-->